### ISSUE TITLE
Extra packages needed?

### ISSUE THREAD

**Issue by e-koch** [Astroua/casa-deploy#1]
@tetarenk - When you have a chance, can you post a link to the other package you need?

**Comment by tetarenk** [comment]
extra packages:
1. python packages—> jdcal,pyfits,astropy; I just usually use casa-python (https://github.com/radio-astro-tools/casa-python) to install these within casa but you need a separate python distribution to use casa-python so then you need to install the anaconda distribution as well
2. analysis utilities—> instructions here https://casaguides.nrao.edu/index.php?title=Analysis_Utilities https://casaguides.nrao.edu/index.php?title=Analysis_Utilities; just need to download the tarball, unpack it and append a few lines to .casa/init.py file (make sure to add the import statement in the init file cause I don’t have it in my script)
3. uvmultifit—>http://nordic-alma.se/support/software-tools http://nordic-alma.se/support/software-tools; instructions in the linked tarball, but essentially you need to compile the C++ module for which you need gcc and g++, as well as the gsl libraries (1st answer here—> http://askubuntu.com/questions/490465/install-gnu-scientific-library-gsl-on-ubuntu-14-04-via-terminal), and then append a few lines to the .casa/init.py again (make sure to add the import statement in the init file too).

Let me know if you have any questions.

---

Alex Tetarenko
PhD Student
Department of Physics
University of Alberta
Edmonton, Canada
http://www.ualberta.ca/~tetarenk http://www.ualberta.ca/~tetarenk

**Comment by e-koch** [comment]
@tetarenk - Should be good to go now! Can you do a quick test with the new image? Something small that uses a bit of each package would be great (I've tested CASA a bit already). Not too critical so no rush.
